{% import '.cookiecutter_includes/license/__init__.j2' as license_macros with context %}
{{- license_macros.license_header.create(
	cookiecutter.license,
	cookiecutter.author,
	cookiecutter.project_slug,
	file_name='dependency-check.yml',
	comment_style='hash') -}}
---
name: Deptry Dependency Check

on: [push, pull_request]

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deptry
        run: |
          make python-install

      - name: Run dependency check
        run: |
          make dependency-check
