{% import '.cookiecutter_includes/license/__init__.j2' as license_macros with context %}
{{- license_macros.license_header.create(
	cookiecutter.license,
	cookiecutter.author,
	cookiecutter.project_slug,
	file_name='lint-check.yml',
	comment_style='hash') -}}
---
name: lint-check

on: [push, pull_request]

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Project Dependencies
        run: |
          make python-install

      - name: Run Ruff Lint Check
        run: |
          make ruff-lint-check  # Check formatting with ruff

      - name: Run Toml Lint Check
        run: |
          make toml-lint-check # Check formatting with tomllint

      - name: Run YAML Lint Check
        run: |
          make yaml-lint-check  # Check formatting with yamllint

      - name: Run Ansible Lint Check
        run: |
          make ansible-lint-check  # Check formatting with ansible-lint
