{% import '.cookiecutter_includes/license_header.j2' as license_macros with context %}
{{- license_macros.license_header(
	cookiecutter.license,
	cookiecutter.author,
	cookiecutter.project_slug,
	file_name='spellcheck.yml',
	comment_style='hash') -}}
---
name: Codespell Spellcheck

on: [push, pull_request]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install codespell
        run: |
          make install

      - name: Run spellcheck
        run: |
          make spellcheck
