# tomllint
---
name: Cookiecutter Template Tomllint Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tomllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Tomllint
        run: |
          make install

      - name: Render Cookiecutter Template
        run: |
          make render-cookiecutter
      - name: Lint Toml files in rendered template.
        run: |
          make toml-lint-check
